# Generated by Django 4.2.5 on 2024-01-03 11:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=110, unique=True)),
                ('password', models.CharField(max_length=110)),
                ('role', models.CharField(max_length=110)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_authenticated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonUserToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='Users.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=110, unique=True)),
                ('firstName', models.CharField(max_length=110)),
                ('familyName', models.CharField(max_length=110)),
                ('email', models.CharField(max_length=110)),
                ('password', models.CharField(max_length=110)),
                ('profile_picture', models.ImageField(blank=True, default='media/profile_pics/default_profile_pic.jpg', null=True, upload_to='profile_pics')),
                ('edit_count', models.IntegerField(default=0)),
                ('delete_count', models.IntegerField(default=0)),
                ('validate_count', models.IntegerField(default=0)),
                ('adminId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.admin')),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=' ', max_length=110, unique=True)),
                ('firstName', models.CharField(max_length=110)),
                ('familyName', models.CharField(max_length=110)),
                ('email', models.CharField(max_length=110)),
                ('password', models.CharField(default=' ', max_length=110)),
                ('profile_picture', models.ImageField(blank=True, default='media/profile_pics/', null=True, upload_to='media/profile_pics')),
                ('favorite_articles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=110), default=list, size=None)),
                ('userId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='userId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
    ]
