# Generated by Django 4.2.5 on 2023-12-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='imgUrl',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='imgUrl',
        ),
    ]
