# Generated by Django 4.2.5 on 2024-01-03 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favorite_articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=110), default=list, size=None),
        ),
    ]
