# Generated by Django 4.2.5 on 2023-12-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=' ', max_length=110),
        ),
        migrations.AddField(
            model_name='client',
            name='userName',
            field=models.CharField(default=' ', max_length=110),
        ),
    ]
