# Generated by Django 4.2.5 on 2023-12-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='userName',
            field=models.CharField(default=' ', max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='userName',
            field=models.CharField(max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=110, unique=True),
        ),
    ]
