# Generated by Django 4.2.5 on 2023-12-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_client_favorite_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='favorite_articles',
        ),
        migrations.RemoveField(
            model_name='client',
            name='imgUrl',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pics/', null=True, upload_to='media/profile_pics'),
        ),
        migrations.AddField(
            model_name='moderator',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pics/default_profile_pic.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
