# Generated by Django 4.2.5 on 2023-12-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_nonusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonusertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='Users.user', verbose_name='user'),
        ),
    ]
