# Generated by Django 4.2.5 on 2023-12-29 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_client_favorite_articles_remove_client_imgurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favorite_articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=110), default=list, size=None),
        ),
    ]
