# Generated by Django 4.2.5 on 2023-12-30 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favorite_articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=110), default=list, size=None),
        ),
        migrations.AddField(
            model_name='moderator',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
    ]
