version: '3'

# containers that make the application
services:
  frontend:
    build:
      context: ./frontend/Articles-igl-engine-frontend
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend/articles_igl_engine
    ports:
      - "8000:8000"
    depends_on:
      - frontend
