# Generated by Django 4.2.5 on 2023-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('url_pdf', models.TextField()),
                ('release_date', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['article_id'], name='article_pkey')],
            },
        ),
    ]
