# Generated by Django 4.2.5 on 2023-12-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='adminId',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='userId',
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
