# Generated by Django 4.2.5 on 2023-12-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
