# Generated by Django 4.2.5 on 2023-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_article_authors_article_bibliographie_article_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.TextField(default='[]', max_length=255),
        ),
    ]
